---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The Naming of Cats is a difficult matter,  
It isn’t just one of your holiday games;  
You may think at first I’m as mad as a hatter. When I tell you, a cat must have THREE DIFFERENT NAMES.  
First of all, there’s the name that the family use daily,  
Such as Peter, Augustus, Alonzo, or James,  
Such as Victor or Jonathan, George or Bill Bailey —  
All of them sensible everyday names.  
There are fancier names if you think they sound sweeter,  
Some for the gentlemen, some for the dames:  
Such as Plato, Admetus, Electra, Demeter —  
But all of them sensible everyday names.  
But I tell you, a cat needs a name that’s particular,  
A name that’s peculiar, and more dignified,  
Else how can he keep up his tail perpendicular,  
Or spread out his whiskers, or cherish his pride?  
Of names of this kind, I can give you a quorum,  
Such as Munkstrap, Quaxo, or Coricopat,  
Such as Bombalurina, or else Jellylorum —  
Names that never belong to more than one cat.  
But above and beyond there’s still one name left over,  
And that is the name that you never will guess;  
The name that no human research can discover —  
But THE CAT HIMSELF KNOWS, and will never confess.  
When you notice a cat in profound meditation,  
The reason, I tell you, is always the same:  
His mind is engaged in a rapt contemplation  
Of the thought, of the thought, of the thought of his name:  
His ineffable effable  
Effanineffable  
Deep and inscrutable singular Name.  